language: ruby
rvm:
- 2.1.2
- 2.0.0
- 1.9.3

before_script:
  - mysql -e 'create database paperbacks_test;'
  
script: 
  - bundle exec rake db:schema:load
  - bundle exec rake
  
after_failure:
  - "mysql -e 'show databases;'"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"