sudo: false
language: ruby

rvm:
- 2.2.1
- 2.2.2

before_script:
- psql -c 'create database paperbacks_test;' -U postgres

script:
- bundle exec rake db:schema:load
- bundle exec rake spec

after_failure:
- echo $RAILS_ENV
- bundle exec rake --version

env:
- DATABASE_URL="postgres://postgres:@localhost/paperbacks_test"
- APP_DOMAIN=localhost:3000

deploy:
  provider: heroku
  master: paperbacks
  run:
  - "rake db:migrate"
  api_key:
    secure: CEU7dWldr/FlSOnT0ta5BglntzB3hlNVtVwNGnOdHWNS5mOLbhbFwpYK846xINElnPC4s8bZ/XZzsmM6euYZ5O/Z83iRJal8s6Vr7LWg6T1+HSdVL7qO42tLMTKl3eQJXObwo2E4wkOxq9lfYfTts+GEBpAAk5PEig7PkOTm6qE=
